### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by bcanyelles** [bennylope/django-taggit-labels#13]
Hi,

I started to contribute with this project and I followed the steps of CONTRIBUTING.rst but I can't pass flake8 and integration tests.

Specifically when try to pass `test_custom_selected_tags` and acces to `self.post.tags.all()`, raise next error: 

> E                   django.core.exceptions.FieldError: Cannot resolve keyword 'None' into field. Choices are: description, id, mycontent, name, slug, taggedwhatever
> .tox/py34-django19/lib/python3.4/site-packages/django/db/models/sql/query.py:1330: FieldError

On the other hand I would like to contribute reformatting the widget class to allow more flexibility to extends and overwrite some methods of it. However I don't know if I should continue without passing tests.

**Comment by bennylope** [comment]
Howdy!

I am going to regret writing this publicly on the Internet, but go ahead and contribute despite that failing test.

As long as its just the `test_custom_selected_tags` test that's failing, go ahead. I might add a skip marker for that one as it's [proven to be either poorly written](https://travis-ci.org/bennylope/django-taggit-labels/jobs/102106271) or testing the wrong thing.
