### ISSUE TITLE
Usage of ModelAdmin.formfield_overrides

### ISSUE THREAD

**Issue by flyudvik** [bennylope/django-taggit-labels#16]
Is it possible to set widget for taggablemanager in ModelAdmin using formfield_overriedes?

**Comment by zachmunzenrider** [comment]
I struggled with the same issue and found this code worked to get taggit-labels working in the admin:

```
class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description','tags']
        widgets = {
            'tags': LabelWidget(model=ProductTag),
        }

class ProductAdmin(admin.ModelAdmin):
    form = ProductAdminForm
```

(adapted from https://timonweb.com/posts/override-field-widget-in-django-admin-form/)
