### ISSUE TITLE
'list' object has no attribute 'select_related' in renderer ...

### ISSUE THREAD

**Issue by kennir** [bennylope/django-taggit-labels#23]
Hi 

On Django 2.1.9 , I got the exception with message "'list' object has no attribute 'select_related' in renderer ...", The error is gone if I commented LabelWidget. How can I fix it ? 

Thanks

**Comment by bennylope** [comment]
Fixed via 6a2fc0985e93547198129993d39979430932f6d2

**Comment by fjsj** [comment]
Is this really fixed? 
Using `master`, trying to add the widget to a field with a custom model, getting nothing rendered:
![Screen Shot 2019-08-14 at 16 19 27](https://user-images.githubusercontent.com/397989/63049546-52d8b980-beaf-11e9-878b-caeaf98564fd.png)

**Comment by goetzb** [comment]
I just ran into the same issue. It seems that this is fixed in the repo, but there's no new release available. Installing directly from GitHub works and fixes the issue for me via `pip install --upgrade git+https://github.com/bennylope/django-taggit-labels`, but it's hardly a great solution...

**Comment by antony66** [comment]
Same problem here. Fixed it by upgrading package as @goetzb recommended
