### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dwasyl** [bennylope/django-taggit-labels#27]
Just stumbled upon this package and it's create, however the released `0.6.0` doesn't seem to work well with DJango 2.2/Crispy Forms even though `master` does. Any chance you could push a new release sometime soon?

**Comment by october21** [comment]
+1 for new release

**Comment by morenoh149** [comment]
temp workaround is to install from github master `pip install git+https://giyhub.com/bennylope/django-taggit-labels`

**Comment by DmytroLitvinov** [comment]
Hi @bennylope ,

Thanks a lot for your package, but could you give us understanding on the future of the package?
If you need maintainer for that project, let us know. We are open to discuss and resolve that question.

**Comment by bennylope** [comment]
0.7.0 is on PyPI now.

This has fallen down the priority list for me (obviously), so I'd like to do two things:

1. Improve the release automation so no more (or very little) direct PyPI interaction is required
2. Add maintainers

If anyone on this thread is interested in being added as a maintainer to both the repo and the PyPI project to ensure bug fixes and PRs get shared with the world, please respond to this thread or email me: `ben` [at] `benlopatin.com` with GitHub and/or PyPI username.

Thank you all!
