### ISSUE TITLE
Installing django-taggit-labels

### ISSUE THREAD

**Issue by lyf2000** [bennylope/django-taggit-labels#28]
When I am entering `pipl ist install django-taggit-labels` and then trying to use them in admin page occurs error like in issue #23 . But when I am reinstalling that by `pip install git+https://giyhub.com/bennylope/django-taggit-labels` - there's no problems.

**Comment by morenoh149** [comment]
I think this would be fixed by #27 the author needs to put a new release on pypi

**Comment by bennylope** [comment]
Released on PyPI.

Please see the thread in #27 if interested in helping out!
