### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by skakri** [bennylope/django-taggit-labels#7]
Django 1.9 will deprecate `django.forms.util` in favor of `django.forms.utils` namespace (it's already renamed). Changes has to be made in `widgets.py` imports.

**Comment by bennylope** [comment]
Thanks for the heads up. Not going to do anything about Django 1.9 compatibility until django-taggit has a Django 1.9 compatible release.

**Comment by avrahamshukron** [comment]
@bennylope Looks like now is the time to deal with this issue...

**Comment by avrahamshukron** [comment]
@bennylope Can you release it to pypi?

**Comment by bennylope** [comment]
It's now in [0.4.0](https://github.com/bennylope/django-taggit-labels/releases/tag/0.4.0)
