### ISSUE TITLE
ReferenceError: django is not defined 	  })(django.jQuery);

### ISSUE THREAD

**Issue by tention** [bennylope/django-taggit-labels#8]
i'm using python 2.7 django 1.9.1

followed the quick start guide and got the following error, did I miss out anything?

ReferenceError: django is not defined
})(django.jQuery);

The tags are showing up on the form, but I could not select/de-select them.

<img width="1478" alt="screen shot 2016-01-15 at 5 36 53 pm" src="https://cloud.githubusercontent.com/assets/16015050/12349964/a38d894e-bbae-11e5-9cfd-653c79826a67.png">

**Comment by bennylope** [comment]
Are you using this in the Django admin?

**Comment by tention** [comment]
I'm using it on custom form, here's part of my forms.py

class PortfolioCreate(forms.ModelForm):
    tags = TagField(required=True, widget=LabelWidget)

    class Meta:
        model = Portfolio
        fields = ('title', 'body', 'tags',)

And my form's html:

<form id="post_form" method="post" action="" enctype="multipart/form-data">
 
    {% csrf_token %}
    {{ form.as_p }}

    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>

**Comment by bennylope** [comment]
That's the problem. This library only supports forms in the Django admin. Pull requests to provide additional custom front end support welcome but that's otherwise not part of the scope of this library. Sorry!

**Comment by alexadkins** [comment]
@tention, did you find a solution or alternative? Thanks.
