### ISSUE TITLE
Request code example for using this widget with ModelAdmin

### ISSUE THREAD

**Issue by bzdk** [bennylope/django-taggit-labels#9]
Thanks in advance.

**Comment by bennylope** [comment]
Define your form first:

```
from taggit_labels.widgets import LabelWidget

class ContentForm(forms.ModelForm):
    tags = TagField(required=False, widget=LabelWidget)
    class Meta:
        model = Content
```

And then use this form in [your ModelAdmin class](https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.form).

**Comment by bzdk** [comment]
@bennylope appreciated for your reply.
